[tox]
envlist = py{310,313}-latest,py310-old

[testenv]
deps =
    pytest
    nltk
    python-Levenshtein
commands =
    pytest tests

[testenv:py310-old]
deps =
    pytest
    numpy>=1.17,<1.18
    pandas>=1.5.3,<1.5.4
    scikit-learn>=1.2,<1.3
    joblib>=1.1,<1.2
    scipy>=1.3,<1.4
    nilearn>=0.7,<0.8
    nltk
commands =
    pytest tests
