sphx_glr_python_to_jupyter.py plot_using_trained_model.py
sphx_glr_python_to_jupyter.py minimal_example.py
sphx_glr_python_to_jupyter.py training_neuroquery.py
sphx_glr_python_to_jupyter.py reverse_search_from_brain_maps_to_terms.py
mv *.ipynb ../
